USE [tempdb]
GO
DBCC FREEPROCCACHE
DBCC DROPCLEANBUFFERS 
DBCC FREESYSTEMCACHE ('ALL')
DBCC FREESESSIONCACHE
DBCC SHRINKDATABASE(tempdb, 50)
DBCC SHRINKFILE ('tempdev') 
DBCC SHRINKFILE ('templog') 
GO